# The format version is an indicator of the compatibility of third-party exercises with the
# Rustlings program.
# The format version is not the same as the version of the Rustlings program.
# In case Rustlings makes an unavoidable breaking change to the expected format of third-party
# exercises, you would need to raise this version and adapt to the new format.
# Otherwise, the newest version of the Rustlings program won't be able to run these exercises.
format_version = 1

# Optional multi-line message to be shown to users when just starting with the exercises.
welcome_message = """
'                      __  ___                 
'     _______  _______/ /_/ (_)___  ____ ______
'    / ___/ / / / ___/ __/ / / __ \\/ __ `/ ___/     ~
'   / /  / /_/ (__  ) /_/ / / / / / /_/ (__  )     ___
'  /_/   \\__,_/____/\\__/_/_/_/ /_/\\__, /____/     ['_']  
'                                /____/       /=) zh-CN (=\\  
'                                                 -----
'                                                 || ||
'                                                 ~~ ~~
"""

# Optional multi-line message to be shown to users after finishing all exercises.
final_message = """+----------------------------------------------------+
        ~
      ['_']  
  /=) zh-CN (=\\  >>干得漂亮，休息一会吧~
      -----
      || ||
      ~~ ~~
"""

# Repeat this section for every exercise.
[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "intro1"

# Optional directory name to be provided if you want to organize exercises in directories.
# If `dir` is specified, the exercise path is `exercises/DIR/NAME.rs`
# Otherwise, the path is `exercises/NAME.rs`
dir = "00_intro"

# Rustlings expects the exercise to contain tests and run them.
# You can optionally disable testing by setting `test` to `false` (the default is `true`).
# In that case, the exercise will be considered done when it just successfully compiles.
test = false

# Rustlings will always run Clippy on exercises.
# You can optionally set `strict_clippy` to `true` (the default is `false`) to only consider
# the exercise as done when there are no warnings left.
# strict_clippy = false

# A multi-line hint to be shown to users on request.
hint = """在终端键入`n`并回车进入下一个练习。"""
skip_check_unsolved = true

[[exercises]]
name = "intro2"
dir = "00_intro"
test = false
hint = """提供打印功能的宏是`printline!`吗？看看编译器提示了什么"""

